### ISSUE TITLE
Questions on training data

### ISSUE THREAD

**Issue by adithyaiyer1999** [THUDM/Inf-DiT#8]
Hi!

Thanks for your great work. I had 2 questions regarding the dataset you trained on.

1. Would you be releasing the exact post filtration data the final model was trained on?
2. Could you give me a rough estimate of how many images were present in your final training dataset?

Thanks again!
Adi

**Comment by yzy-thu** [comment]
The training dataset is approximately 145M images with resolution higher than 1024, of which 140M come from laion-highresolution and can be directly accessed from Hugging Face. The remaining part has no plan to release, but I believe this part is not important for training.

**Comment by adithyaiyer-morphic** [comment]
Thanks! Makes sense.
